### PR TITLE
RHIROS-700 | Add latest RHEL releases for filtering

### PR DESCRIPTION
**Pull request by saltgen**
Changes:

1. Updated constants.js with RHEL 8.6, 9.0

Additional:

- NA

### CODE REVIEW

**Comment by kgaikwad** [comment]
Backend side PR - https://github.com/RedHatInsights/ros-backend/pull/261

**Review by r14chandra — APPROVED** [review]

**Review by PreetiW — APPROVED** [review]
Thanks @saltgen for the PR.
I had tested the frontend changes in EE and it looks good. Once the backend changes are merged please do an end to end test before merging the PR! 🙌🏻

**Pull request merged**
