### PR TITLE
Prod-Beta deployment; 8th Jun 2023

### PR DESCRIPTION
**Pull request by saltgen**
[RHIROS-1006](https://issues.redhat.com/browse/RHIROS-1006) - Migrate the Systems report PDF to new PDF service
[RHIROS-1125](https://issues.redhat.com/browse/RHIROS-1125) - Unable to see "Related Knowledgebase Article" section on ROS System Page

### CODE REVIEW

**Review by r14chandra — APPROVED** [review]

**Comment by r14chandra** [comment]
Deploy job is failing

**Review by PreetiW — APPROVED** [review]
LGTM 💯

**Comment by saltgen** [comment]
Closing this out, will re-open new PR with the same changes. This is due to Travis error.

Ref: https://stackoverflow.com/questions/39140800/the-command-eval-git-fetch-origin-refs-pull-7-merge-failed

**Pull request closed without merging**
