### PR TITLE
RHIROS 1216 filter by group

### PR DESCRIPTION
**Pull request by PreetiW**
## RHIROS 1216 filter by group:boom:

RHIROS 1216 filter by group https://issues.redhat.com/browse/RHIROS-1216

## Why do we need this change? :thought_balloon:

Please include the __context of this change__ here.

## Documentation requires update? :memo:

- [ ] Yes
- [x] No

## Security Checklist :lock:

Upon raising this PR please go through [RedHatInsights/secure-coding-checklist](https://github.com/RedHatInsights/secure-coding-checklist)

## :guardsman: Checklist :dart:

- [ ] Bugfix
- [x] New Feature
- [ ] Refactor
- [ ] Unittests Added
- [ ] DRY code
- [ ] Dependency Added

## Additional :mega:

Feel free to add any other relevant details such as __links, notes, screenshots__, here.

### CODE REVIEW

**Comment by upadhyeammit** [comment]
Hello @PreetiW I tested the functionality and its working as expected, however when I try to reset filters and if the request is slow for some moment I see "no matching systems found" and then it loads all the systems. I tried to catch that in screencast but was not able too,sometimes its quick and sometimes its not. Its not blocker but if its something we can avoid then that will be good!

**Comment by PreetiW** [comment]
Thank you @upadhyeammit for reviewing the PR, I will create a separate card for scenario with slow internet connection.

**Review by saltgen — APPROVED** [review]
LGTM, thanks @PreetiW!

**Comment by PreetiW** [comment]
Thank you for the review @upadhyeammit & @saltgen 🙌🏻 merging the PR!

**Pull request merged**
