### PR TITLE
RHIROS-666 added frontend.yaml file in deploy folder

### PR DESCRIPTION
**Pull request by PreetiW**
### Description

**Jira:** https://issues.redhat.com/browse/RHIROS-666

**Documentation**: 
https://consoledot.pages.redhat.com/docs/dev/getting-started/frontend-migration.html#_deploy

### CODE REVIEW

**Review by r14chandra — COMMENTED** [review]
Looks awesome 👍🏻 Thanks @PreetiW! To work with the ephemeral environment we need to add a [template](https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/data/services/insights/ros/deploy-clowder.yml#L41) here as well (refer the same doc). Let me know if you have already raised an MR there.

**Review by r14chandra — APPROVED** [review]

**Comment by PreetiW** [comment]
> Looks awesome 👍🏻 Thanks @PreetiW! To work with the ephemeral environment we need to add a [template](https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/data/services/insights/ros/deploy-clowder.yml#L41) here as well (refer the same doc). Let me know if you have already raised an MR there.

Thank you @r14chandra for reviewing the PR 🙌🏻 Yes correct we will need another PR under app-interface, once this PR is merged I will open that one as it has reference of this file and will share the PR link 💯

**Review by BlakeHolifield — APPROVED** [review]
Looks great!

**Comment by PreetiW** [comment]
Thank you for the review @r14chandra and @BlakeHolifield 🙌🏻 
Merging this PR!

**Pull request merged**
