### PR TITLE
updated packages with vulnerabilities

### PR DESCRIPTION
**Pull request by PreetiW**
## updated packages with vulnerabilities :boom:

updated packages with vulnerabilities
Jira: https://issues.redhat.com/browse/RHIROS-1095

## Why do we need this change? :thought_balloon:

few of the packages we are using got vulnerabilities and this PR updates those packages to fix the same.

## Documentation requires update? :memo:

- [ ] Yes
- [x] No

## Security Checklist :lock:

Upon raising this PR please go through [RedHatInsights/secure-coding-checklist](https://github.com/RedHatInsights/secure-coding-checklist)

## :guardsman: Checklist :dart:

- [ ] Bugfix
- [ ] New Feature
- [ ] Refactor
- [ ] Unittests Added
- [ ] DRY code
- [ ] Dependency Added

## Additional :mega:

Feel free to add any other relevant details such as __links, notes, screenshots__, here.

### CODE REVIEW

**Comment by PreetiW** [comment]
@ShivamPandya As discussed can you please do regression testing on this PR 🙌🏻

**Comment by ShivamPandya** [comment]
@PreetiW Tried the image from this PR. LGTM!

**Comment by PreetiW** [comment]
Thanks for testing the PR @ShivamPandya, merging it.

**Pull request merged**
