### PR TITLE
RHINENG-13820 - Update package dependencies

### PR DESCRIPTION
**Pull request by PreetiW**
## PR Title :boom:

Upgraded following dependencies:

- Updates **cookie from 0.6.0 to 0.7.1**
- Updates **express from 4.19.2 to 4.21.1**
- Updates **body-parser from 1.20.2 to 1.20.3**
- Updates **serve-static from 1.15.0 to 1.16.2**
- Updates **send from 0.18.0 to 0.19.0**
- Updates **path-to-regexp from 0.1.7 to 0.1.10**
- Updates **@redhat-cloud-services/frontend-components-config to 6.3.1**  which updates its dependent packages **webpack-dev-serve to 5.1.0** and updates **express to 4.19.2**

-  Bumps [postcss](https://github.com/postcss/postcss) from 8.4.39 to 8.4.47.
-  Bumps [webpack](https://github.com/webpack/webpack) from 5.93.0 to 5.95.0
-  Bumps [micromatch](https://github.com/micromatch/micromatch) from 4.0.5 to 4.0.8.
- Bumps [@babel/preset-react](https://github.com/babel/babel/tree/HEAD/packages/babel-preset-react) from 7.10.0 to 7.25.7.
- Bumps [@patternfly/react-charts](https://github.com/patternfly/patternfly-react) from 7.2.2 to 7.4.3.

**Jiras:**
* [RHINENG-10566](https://issues.redhat.com/browse/RHINENG-10566)
* [RHINENG-13820](https://issues.redhat.com/browse/RHINENG-13820)

Feel free to remove this section from PR description once done.

## Why do we need this change? :thought_balloon:

Please include the __context of this change__ here.

## Documentation requires update? :memo:

- [ ] Yes
- [x] No

## Security Checklist :lock:

Upon raising this PR please go through [RedHatInsights/secure-coding-checklist](https://github.com/RedHatInsights/secure-coding-checklist)

## :guardsman: Checklist :dart:

- [ ] Bugfix
- [ ] New Feature
- [ ] Refactor
- [ ] Unittests Added
- [ ] DRY code
- [ ] Dependency Added

## Additional :mega:

Feel free to add any other relevant details such as __links, notes, screenshots__, here.

### CODE REVIEW

**Review by r14chandra — COMMENTED** [review]
As per the comment added under [RHINENG-10566](https://issues.redhat.com/browse/RHINENG-10566), I don't see any upgrade for `node_modules/webpack-dev-server`. Is it required?

**Comment by kgaikwad** [comment]
> As per the comment added under [RHINENG-10566](https://issues.redhat.com/browse/RHINENG-10566), I don't see any upgrade for `node_modules/webpack-dev-server`. Is it required?

Here, it got updated along with express as part of webpack I guess!
https://github.com/RedHatInsights/ros-frontend/pull/397/files#diff-053150b640a7ce75eff69d1a22cae7f0f94ad64ce9a855db544dda0929316519R22503

**Review by kgaikwad — APPROVED** [review]

**Comment by PreetiW** [comment]
> As per the comment added under [RHINENG-10566](https://issues.redhat.com/browse/RHINENG-10566), I don't see any upgrade for `node_modules/webpack-dev-server`. Is it required?

@r14chandra as mentioned by Kavita, it got updated as part of this commit: https://github.com/RedHatInsights/ros-frontend/pull/397/commits/944eb2bd352866067e406599088ba6175a485ab3

**Review by r14chandra — APPROVED** [review]

**Comment by PreetiW** [comment]
@kgaikwad @r14chandra 
tested the changes locally and it is working fine, hence merging this PR. Thank you both for the review 🙌🏻 

image
image

**Pull request merged**
